# Generated by Django 5.0.4 on 2024-04-12 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.FileField(upload_to='datasets/')),
                ('apercu', models.ImageField(blank=True, null=True, upload_to='dataset_previews/')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_review.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('algorithm', models.CharField(max_length=100)),
                ('model_data', models.FileField(upload_to='models/')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_review.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_review.column')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_review.model')),
            ],
        ),
    ]
