# Generated by Django 5.0.4 on 2024-04-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='status',
            field=models.CharField(choices=[('input', 'Input'), ('target', 'Target')], default='Input', max_length=10),
        ),
    ]
