# Generated by Django 5.0.4 on 2024-04-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_review', '0003_dataset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='algorithm',
            field=models.CharField(choices=[('randomforest', 'RamdomForest'), ('logistic_regression', 'Regression Logistique'), ('decision_tree', 'Arbre de décision'), ('xgboost', 'XGBOOST'), ('svm', 'SVM'), ('igboost', 'IGBOOST')], default='Regression Logistique', max_length=100),
        ),
    ]
