# Generated by Django 5.0.4 on 2024-04-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_review', '0006_alter_model_model_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
    ]
