# Generated by Django 5.0.4 on 2024-05-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_review', '0007_model_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='status',
            field=models.CharField(choices=[('trained', 'Entrainé'), ('untrained', 'Non entrainé')], default='untrained', max_length=100),
        ),
    ]
